language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - "7"
  - "8"
  - "9"
  - "10"

install:
  - npm install

script:
  - npm run build
  - cd build/
  - zip -r build-${TRAVIS_BUILD_NUMBER}-${TRAVIS_JOB_NUMBER}.zip ./*

addons:
  artifacts: true
  working_dir: build