language: node_js
os:
- linux
- osx
node_js:
- node
- lts/*
- '7'
- '8'
- '9'
- '10'
install:
- npm install
script:
- npm run build
- cd build/
- zip -r sc2pte-build.zip ./*
addons:
  artifacts: true
  working_dir: build
before_deploy:
- git config --local user.name "Łukasz Wójcik"
- git config --local user.email "lwojcik@lukem.net"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: cmV1IDhLdc0mA0VZboeN0Ffxvyd/XsKrQfb3grGbJl+MT9M8PitaPo24o0aocks6vAjabwdQ1hcU78qfeVk0ZQoEqW0jezol1WXyJPP90YONuwpCrzWniy6bAEIDf8hE5MX1LrAjSd322bDYSJxUzlSFIwjQpKMHdmw6pn5ZUl7uOVlWUA53aC3JkuCgFlZqA6x7jvrpcilID41LHIHfbnAEEQKkiK6o20W2mfaaMz5hMVCL8l6jkLkO87GA4RawIxV1QiLboEhVg8SJY2oADVn8Q7iA1uhkkIAa18AZPjpJToVYxEVajv9zRJ6ByE+dKvCcvGS4wFgCSMuC3azFl6rA0rczQSm6x7mOQfIbWVqh4Kb84I0o/KRP9hoWu7gLAm1wFKlKzilzxyzeY6icdmWzqyICRFG8zbnSD0fWKvcsrDzShaEDsvcofM2A1ot3xrUAY86TljlTn75HtXRhEQfrs5QsYcu/Ync19NE9aS2NPvn4ut4H8fDLmkMGliHioc//S/o7widFN4RUZbQc6VPFTTQl87DEqssJhzI1znFKm8urCwXP7TV09aQvGc0nfReaFM34Gh3BuRZJgCiTVDm8OhqaqQjWp9oyOmP5TqU4QHSLvsuyHQhLczsty+dVkTyY1a6J0Us7GRMZE3bawcLGKYQx2bJabQ9byfJHXnM=
  file: ./build/sc2pte-build.zip
  on:
    repo: lukemsc/sc2profile-twitch-extension-frontend
    branch: master
    condition: $TRAVIS_NODE_VERSION = 8