environment:
  matrix:
    - nodejs_version: "lts"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run build

test_script:
  - node --version
  - npm --version

build: off